### ISSUE TITLE
problems with tuples

### ISSUE THREAD

**Issue by joss75321** [suzaku-io/boopickle#41] opened 2015-09-18 11:08 UTC
```
import boopickle.Default._

sealed trait S
case class PStroke(colour: String) extends S
case class PImage( pair: (Int,String), ops: Seq[S])
case class OptImg(i: Option[PImage])

object TP {

  implicit val picklerS = compositePickler[S].addConcreteType[PStroke]

  def foo(o: OptImg) = {
    Pickle.intoBytes(o)
  }
}
```

Lovely library, many thanks, but finding some weird stuff. There's no way that I can find to serialize OptImg.. if one takes out 'pair' from PImage, the problem goes away

**Comment by ochrons** [comment] 2017-09-12 20:12
Probably a duplicate of #21

**Closed by ochrons** 2017-09-12 20:12 UTC
Labels: duplicate
